server:
  port: 9091
spring:
  application:
    name: ssm
  profiles:
    active: devx
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://210.38.139.237:3306/course?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Itaem@488
      initial-size: 5
      validation-query: 'select 1'
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis:
  type-aliases-package: com.he.ssm.entity
  mapper-locations: classpath*:mybatis/**/*.xml

logging:
  config: classpath:logback-spring.xml

he:
  upload:
    dir: /upload
    dirResourcePath: /static/res
    allowMaxFileNameLength: 100
    allowMaxFileSize: 1073741824
    allowExt: bmp,gif,jpg,jpeg,png,doc,docx,xls,xlsx,ppt,pptx,html,htm,txt,rar,zip,gz,bz2,pdf,swf,flv ,swf,flv,mp3,wav,wma,wmv,mid,avi,mpg,asf,rm,rmvb,mp4
    ctx: http://210.38.139.237:${server.port}


redis:
  host: localhost
  port: 6379
  timeout: 10
  pool-max-wait: 500
  pool-max-idle: 500
  pool-max-total: 1000

